### ISSUE TITLE
Animate over existing page

### ISSUE THREAD

**Issue by TiborUdvari** [jonhue/turbolinks-animate#27]
**Is your feature request related to a problem? Please describe.**
I would like to keep the existing page in the background while an animation completes. As it is I think it is quite weird that the page disappears altogether and a new one comes in from an animation standpoint.

**Describe the solution you'd like**
Animate the new page in and clear the old one only after the animation has completed. 

**Describe alternatives you've considered**
In case this is technically not possible, maybe taking a screenshot of the current page contents to visually achieve this feeling.

**Comment by jonhue** [comment]
Good suggestion, but I don't think it is possible to implement this. The problem here lies with how browsers render pages. The goal of this package is to hide the ugly and abrupt removal and addition of content the browser performs. It hides content before being removed and displays it after it has been added.

Therefore, as much as I like your suggestion, I don't think it is feasible as of now. Feel free though to submit a pull request to prove me wrong. :)
